#!/usr/bin/env bash

bin=`dirname "${BASH_SOURCE-$0}"`
bin=`cd "$bin"; pwd`

# set default config
DST="/tmp"
HOSTS="localhost"

# load config
if [[ -s "./.ezsync.conf" ]]; then
    source "./.ezsync.conf"
elif [[ -s "$HOME/.ezsync.conf" ]]; then
    source "$HOME/.ezsync.conf"
elif [[ -s "$bin/.ezsync.conf" ]]; then
    source "$bin/.ezsync.conf"
else
    echo "WARN: couldn't load .ezsync.conf, use $HOSTS:$DST."
fi

SRC=$(pwd)

[[ -f $SRC/.rsync-filter ]] && FILTER_OPT="-F $SRC/.rsync-filter"

for host in ${HOSTS}; do
    echo "sync: $SRC => $host:$DST"
    rsync -a $FILTER_OPT $@ --rsync-path="mkdir -p $DST && rsync" $SRC/ $host:$DST
done
