#!/usr/bin/env bash

bin=`dirname "${BASH_SOURCE-$0}"`
bin=`cd "$bin"; pwd`

if [ -z "$1" ]; then
    echo "USAGE: $0 TARGET [ARGS]"
    exit -1
fi

# set default config
DST="/tmp"
HOSTS="localhost"

# load config
if [[ -s "./sync.conf" ]]; then
    source "./sync.conf"
elif [[ -s "$HOME/.sync.conf" ]]; then
    source "$HOME/.sync.conf"
elif [[ -s "$bin/sync.conf" ]]; then
    source "$bin/sync.conf"
else
    echo "WARN: no sync.conf in current directory, use $HOSTS:$DST."
fi

SRC=$(readlink -m "$1")
shift


for host in ${HOSTS}; do
    echo "rsync $2 $SRC to $host:$DST"
    rsync -rta $@ --rsync-path="mkdir -p $DST && rsync" $SRC $host:$DST
done
