#!/usr/bin/env bash

bin=`dirname "${BASH_SOURCE-$0}"`
bin=`cd "$bin"; pwd`

# set default config
DST="/tmp"
HOSTS="localhost"

# load config
if [[ -s "./sync.conf" ]]; then
    source "./sync.conf"
elif [[ -s "$HOME/.sync.conf" ]]; then
    source "$HOME/.sync.conf"
elif [[ -s "$bin/sync.conf" ]]; then
    source "$bin/sync.conf"
else
    echo "WARN: couldn't load sync.conf, use $HOSTS:$DST."
fi

SRC=$(pwd)

[[ -f $SRC/.rsync-filter ]] && FILTER_OPT="-F $SRC/.rsync-filter"

for host in ${HOSTS}; do
    echo "rsync: $SRC => $host:$DST"
    rsync -a $FILTER_OPT $@ --rsync-path="mkdir -p $DST && rsync" $SRC/ $host:$DST
done
